StartupEvents.registry('item', event => {
	//Andesite grinding Ball
	event.create('andesite_ball')
		.displayName('Andesite Grinding Ball')
		.maxStackSize(32)
		.texture("kubejs:item/processing/andesite_ball")
		//.maxDamage(16)
		
	//milled ores
	event.create('milled_iron')
		.displayName('Milled Raw Iron')
		.texture("kubejs:item/milled_ore/milled_iron")
	event.create('milled_gold')
		.displayName('Milled Raw Gold')
		.texture("kubejs:item/milled_ore/milled_gold")
	event.create('milled_copper')
		.displayName('Milled Raw Copper')
		.texture("kubejs:item/milled_ore/milled_copper")
	event.create('milled_zinc')
		.displayName('Milled Raw Zinc')
		.texture("kubejs:item/milled_ore/milled_zinc")
	event.create('milled_coal')
		.displayName('Milled Raw Coal')
		.texture("kubejs:item/milled_ore/milled_coal")
		.burnTime(3200)
})